### ISSUE TITLE
Crashes when started

### ISSUE THREAD

**Issue by ghost** [dwizard/rocket#1]
Traceback (most recent call last):
  File "C:\Users\Nathan\Desktop\Programming\Rocket\Interpreter\rocket.py", line 8
    import rocket.lexer
  File "C:\Users\Nathan\Desktop\Programming\Rocket\Interpreter\rocket\lexer.py", line 75
    print(" % (t.value[0], t.lexpos, t.lineno))
                                              ^
SyntaxError: EOL while scanning string literal

**Comment by catb0t** [comment]
It's just an unclosed string literal; why don't you add the quote and make a pull request? Maybe dwizard will appear to merge it.

**Comment by davidwitten** [comment]
Oops yeah we'll fix it
